name: young_motion
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  another_stepper: ^1.2.2
  auto_route: ^8.1.3
  bloc: ^8.1.4
  carousel_slider: ^4.2.1
  dio: ^5.4.3+1
  dropdown_model_list: ^2.1.1
  equatable: ^2.0.5
  ff_bloc: ^1.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_expandable_text: ^1.0.0
  flutter_rating: ^2.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  jiffy: ^6.3.1
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
